### ISSUE TITLE
messed import express

### ISSUE THREAD

**Issue by maxim-s-barabash** [rjbma/dtsgenerator-express-route-types#9]
tslib@2.3.1
dtsgenerator@3.13.2
dtsgenerator-express-route-types@0.2.1
    
   I do not know why, but such an import is generated for me
   
**what have**
   ```
   import { RequestHandler  as  } from "express";
   ```
   
**what expect**
   ```
   import { RequestHandler } from "express";
   ```
 
**my version of the fix**
  
```typescript
   function createImportStatement(factory: ts.NodeFactory) {
    const namedImport = factory.createNamedImports([
        factory.createImportSpecifier(
            false,
            undefined,
            factory.createIdentifier('RequestHandler')
        ),
    ]);
    const importExpress = factory.createImportDeclaration(
        undefined,
        undefined,
        factory.createImportClause(false, undefined, namedImport),
        factory.createStringLiteral('express')
    );
    return importExpress;
}
```

**Comment by rjbma** [comment]
Seems this problem occurs when using the latest version of typescript, in which the signature of the `createImportSpecifier` function has changed. I've updated the dependencies on **package.json** and applied your suggested fix, and it seems to work correctly now.

Thanks, and sorry for the for the late reply!
